apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kibana
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - image: kibana:6.2.3
        imagePullPolicy: IfNotPresent
        name: kibana
        ports:
        - containerPort: 5601
        livenessProbe:
          httpGet:
            path: /
            port: 5601
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 5601
          initialDelaySeconds: 30
          timeoutSeconds: 5
      restartPolicy: Always
