apiVersion: v1
kind: Service
metadata:
  labels:
    app: kibana
  name: kibana
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    targetPort: 5601
    nodePort: 30961
  selector:
    app: kibana
  type: NodePort
